# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-03 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20180127_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
